### ISSUE TITLE
Is this still needed?

### ISSUE THREAD

**Issue by kkmuffme** [orklah/psalm-insane-comparison#3]
https://psalm.dev/r/3de9e63404

Psalm already reports these issues by default now?
If not, I think it would be worth it to PR it directly into Psalm

**Comment by orklah** [comment]
First issue:
https://psalm.dev/r/3de9e63404?phpVersion=7.1
https://psalm.dev/r/3de9e63404?phpVersion=8.1

Those two links reports the same issue `ERROR: [TypeDoesNotContainType](https://psalm.dev/056) - 5:4 - Type 0 for $b is never ~string(banana)` But it's wrong: https://3v4l.org/MeRUE

The particular logic of this comparison changing between version has not been implemented in Psalm (this is a point that could be added with a PR).

Second issue:
https://psalm.dev/r/665f30060d

Psalm does not report any error for this code (while this plugin should). This is because the expression could be true but could also be false in any php version.

This won't ever be added in Psalm because it's not an error per se. If you have $a with a `0|1` type, checking `0 == 'banana'` is correct, whether you run PHP7 or PHP8. you just have to have the correct assumption in mind.

The error this plugin emits is just a tool to find expression that could change behavior between versions. The code is not inherently good or bad. And this is why it can't be added in Psalm. For a code designed from the start for PHP8, the expression is perfectly fine
